openapi: 3.0.0
info:
  title: Bhashini Translation API
  description: Bhashini Translation API
  version: 1.0.0
servers:
  - url: http://localhost:3002
components:
  schemas:
    NMT:
      type: object
      properties:
          sourceLanguage:
              type: string
              description: Source Language
          targetLanguage:
              type: string
              description: Target Language
          text:
              type: string
              description: Text to translate
    TTS:
      type: object
      properties:
          sourceLanguage:
              type: string
              description: Source Language
          text:
              type: string
              description: Text to translate
          gender:
              type: string
              description: Gender choice for voice in audio
    ASR:
      type: object
      properties:
          sourceLanguage:
              type: string
              description: Source Language
          base64String:
              type: string
              description: Audio to convert to text
paths:
  /nmt:
    post:
      summary: Get translation
      description: Get translation from source to target language
      requestBody:
          description: A JSON object containing source and target languages and the text to translate
          content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/NMT'
      responses:
        200:
          description: Success
        500:
          description: Internal Server Error
  /tts:
    post:
      summary: Text to speech
      description: Get a text converted to speech
      requestBody:
        description: A JSON object containing source language, text and gender
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TTS'
      responses:
        200:
          description: A WAV audio file
          content:
            application/audio:
              schema:
                type: string
                format: base64
                description: Base64-encoded contents of the audio
        500:
          description: Internal Server Error
  /asr:
      post:
        summary: Automatic speech recognition
        description: Get a text converted converted from speech
        requestBody:
          description: A JSON object containing source language and text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ASR'
        responses:
          200:
            description: A JSON object containing converted text
          500:
            description: Internal Server Error

